"""
Procurement Guardrails Service

Provides deterministic safety boundaries and risk checks to prevent:
1. Erroneous zero or negative orders.
2. Orders exceeding budget or volume caps (e.g. max quantity or max value).
3. Ordering products not enabled for replenishment.
4. Ordering when no active supplier is linked.
5. Ordering non-pack multiples (e.g., buying 13 tablets when box comes in 10).
6. Placing new orders when existing batches have a severe expiry risk (>50%).
"""

from dataclasses import dataclass
from backend.app.core.config import settings
from backend.app.models.entities import Product, Supplier, ProcurementProposal


@dataclass
class GuardrailResult:
    """
    Data container holding the outcome of guardrail validation.

    Attributes:
        allowed (bool): True if all mandatory checks passed; False if any hard check failed.
        reasons (list[str]): List of blocking error reasons that prevent order placement.
        warnings (list[str]): Non-blocking informational warnings (e.g. below minimum order value).
    """
    allowed: bool
    reasons: list[str]
    warnings: list[str]


class ProcurementGuardrails:
    """
    Deterministic rule-based safety engine.

    Ensures that every proposed or approved procurement order complies with
    financial, operational, supplier, and regulatory packaging policies.
    """

    def validate_proposal(
        self,
        product: Product,
        supplier: Supplier | None,
        qty: float,
        unit_cost: float,
    ) -> GuardrailResult:
        """
        Validate an automated proposal generated by the ProcurementAgent.

        Args:
            product (Product): Canonical product master record.
            supplier (Supplier | None): Chosen supplier master record, or None.
            qty (float): Proposed order quantity in base units.
            unit_cost (float): Cost price per unit (P.Rate).

        Returns:
            GuardrailResult: Whether the proposal is allowed, plus any reasons or warnings.
        """
        reasons: list[str] = []
        warnings: list[str] = []

        # Calculate estimated total purchase value
        order_value = max(0.0, qty) * max(0.0, unit_cost)
        pack = max(1, int(product.pack_size or 1.0))

        # Check 1: Quantity must be positive
        if qty <= 0:
            reasons.append("Quantity must be greater than zero.")

        # Check 2: Quantity must not exceed configured hard ceiling
        if qty > settings.max_proposal_qty_units:
            reasons.append(
                f"Quantity ({qty:g}) exceeds system cap of {settings.max_proposal_qty_units:g} units."
            )

        # Check 3: Total value must not exceed maximum budget cap
        if order_value > settings.max_proposal_value:
            reasons.append(
                f"Proposal value (₹{order_value:,.2f}) exceeds maximum allowable cap of ₹{settings.max_proposal_value:,.2f}."
            )

        # Check 4: Product must be enabled for automated replenishment
        if not product.reorder_enabled:
            reasons.append(f"Product '{product.product_code}' is disabled for automated reordering.")

        # Check 5: Active supplier check (Non-blocking warning; allows user to assign supplier in UI)
        if supplier is None or not supplier.is_active:
            warnings.append("No active supplier is linked to this product. Supplier can be assigned during review.")

        # Check 6: Supplier Minimum Order Value check (Non-blocking warning)
        if supplier and order_value < supplier.min_order_value:
            warnings.append(
                f"Order value (₹{order_value:,.2f}) is below supplier minimum order threshold of ₹{supplier.min_order_value:,.2f}."
            )

        # Check 7: Packaging multiple check (Pharmaceutical strips/boxes cannot be broken)
        if pack > 1 and (qty % pack > 1e-4 and abs((qty % pack) - pack) > 1e-4):
            reasons.append(
                f"Order quantity ({qty:g}) must be a clean multiple of packaging size ({pack})."
            )

        # If there are zero blocking reasons, proposal is allowed
        return GuardrailResult(
            allowed=(len(reasons) == 0),
            reasons=reasons,
            warnings=warnings,
        )

    def validate_approval(
        self,
        proposal: ProcurementProposal,
        product: Product,
        supplier: Supplier | None,
        requested_qty: float,
    ) -> GuardrailResult:
        """
        Validate human reviewer's decision when approving or modifying a proposal.

        Enforces all standard proposal checks plus human workflow constraints:
        - Proposal must currently be in PENDING status.
        - High FEFO expiry risk (>=50%) blocks ordering fresh stock until old stock is resolved.

        Args:
            proposal (ProcurementProposal): Proposal record being reviewed.
            product (Product): Product record.
            supplier (Supplier | None): Supplier chosen by the reviewer.
            requested_qty (float): Approved quantity (as modified or confirmed by human).

        Returns:
            GuardrailResult: Allowed flag and reasons for rejection if blocked.
        """
        # Run base quantitative checks
        result = self.validate_proposal(product, supplier, requested_qty, proposal.unit_cost)

        # Review Check 1: Must be in PENDING state
        if proposal.status != "PENDING":
            result.allowed = False
            result.reasons.append(
                f"Proposal #{proposal.id} is in state '{proposal.status}' (only PENDING proposals can be approved)."
            )

        # Review Check 2: High Expiry Risk block
        if proposal.expiry_risk_score >= 0.50 and requested_qty > 0:
            result.allowed = False
            result.reasons.append(
                f"High FEFO expiry risk ({proposal.expiry_risk_score:.0%}) blocks new purchases until near-expiry stock is cleared."
            )

        return result
